baseURL = "https://techdebtor.io/"
languageCode = "en-us"
title = "The Tech Debtor"
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "Creating tech debt for future generations."
  author = "Travis Boettcher"
  resumeURL = "https://resume.techdebtor.io/"
  githubURL = "https://github.com/travisboettcher"
  linkedinURL = "https://www.linkedin.com/in/travisboettcher/"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20
